# Generated by Django 4.2.6 on 2023-11-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(max_length=10)),
                ('pname', models.CharField(max_length=32)),
                ('price', models.IntegerField(max_length=10)),
                ('qty', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
